# Generated by Django 3.1.5 on 2021-02-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='constructor',
        ),
    ]
