# Generated by Django 3.1.5 on 2021-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20210208_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fastest_laps',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
