# Generated by Django 3.1.5 on 2021-02-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_fastest_laps'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='world_championships',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
