# Generated by Django 3.1.5 on 2021-02-19 01:16

from django.db import migrations
import rgbfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_full_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=rgbfield.fields.RGBColorField(default='#ffffff'),
        ),
    ]
