# Generated by Django 3.1.5 on 2021-02-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
    ]
