# Generated by Django 4.0 on 2021-12-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('driver_number', models.PositiveIntegerField(unique=True)),
                ('points', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=150)),
                ('detail_image', models.CharField(max_length=150)),
                ('flag', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=30)),
                ('podiums', models.PositiveIntegerField()),
                ('points_to_date', models.PositiveIntegerField()),
                ('world_championships', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drivers', to='teams.team')),
            ],
        ),
    ]
