# Generated by Django 3.1.5 on 2021-01-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='flag',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='driver',
            name='podiums',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='points',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='points_to_date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='world_championships',
            field=models.PositiveIntegerField(),
        ),
    ]
