# Generated by Django 3.1.5 on 2021-02-19 01:12

from django.db import migrations
import rgbfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20210206_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='color',
            field=rgbfield.fields.RGBColorField(default='#ffffff'),
        ),
    ]
