# Generated by Django 3.1.5 on 2021-02-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='color',
        ),
    ]
