# Generated by Django 3.1.5 on 2021-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20210120_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='flag',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.CharField(max_length=150),
        ),
    ]
